image: hmctssandbox.azurecr.io/hmcts/plum-batch:latest
environment:
  TEST_VAR: test
  CONFIG_TEMPLATE: "{{ .Release.Name }}-config"
configmap:
  VAR_A: VALUE_A
  VAR_B: VALUE_B
keyVaults:
  "plumsi":
    secrets:
      - test-secret
kind: CronJob
global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  environment: aat
  enableKeyVaults: true
schedule: "*/1 * * * *"
startingDeadlineSeconds: 1800
args:
  - sample
  - another