image: hmctssandbox.azurecr.io/hmcts/plum-batch:latest
environment:
  TEST_VAR: test
  CONFIG_TEMPLATE: "{{ .Release.Name }}-config"
configmap:
  VAR_A: VALUE_A
  VAR_B: VALUE_B
keyVaults:
  "s2s":
    secrets:
      - microservicekey-cmcLegalFrontend
global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  environment: aat
  enableKeyVaults: true
schedule: "*/1 * * * *"
labels:
  sample : sample-value
  another: another-value