{{- $languageValues := deepCopy .Values}}
{{- if hasKey .Values "language" -}}
{{- $languageValues = (deepCopy .Values | merge (pluck .Values.language .Values | first) )}}
{{- end -}}
{{- $jobKind := (default $languageValues.kind  $languageValues.global.jobKind) -}}
{{ if (and $jobKind (eq $jobKind "CronJob")) }}
{{- $globals := $languageValues.global -}}
{{- $concurrentCronJob := (default $globals.concurrentCronJob $languageValues.concurrentCronJob) -}}
---
apiVersion: batch/v1
kind: CronJob
{{ include "hmcts.metadata.v2" .}}
spec:
  schedule: "{{ $languageValues.schedule }}"
  {{- if $concurrentCronJob }}
  startingDeadlineSeconds: {{ int $languageValues.startingDeadlineSeconds }}
  suspend: false
  {{- else }}
  suspend: {{ not $globals.activeCronCluster }}
  startingDeadlineSeconds: {{ $globals.activeCronCluster | ternary int $languageValues.startingDeadlineSeconds 5 }}
  {{- end }}
  {{- if $languageValues.concurrencyPolicy }}
  concurrencyPolicy: "{{ $languageValues.concurrencyPolicy }}"
  {{- end }}
  {{- if $languageValues.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $languageValues.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if $languageValues.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $languageValues.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
{{ include "job.spec.v1" . | indent 4}}
{{- end}}
