{{- $languageValues := deepCopy .Values}}
{{- if hasKey .Values "language" -}}
{{- $languageValues = (deepCopy .Values | merge (pluck .Values.language .Values | first) )}}
{{- end -}} 
{{- $jobKind := (default $languageValues.kind  $languageValues.global.jobKind) -}}
{{ if (and $jobKind (eq $jobKind "CronJob")) }}
{{- $globals := $languageValues.global -}}
{{- $disableActiveClusterCheck := (default $globals.disableActiveClusterCheck $languageValues.disableActiveClusterCheck) -}}
{{- $activeCronCluster := false -}}
{{- if eq (toString $globals.activeCronCluster) "true" -}}
{{- $activeCronCluster = true }}
{{- else }}
{{- $activeCronCluster = false }}
{{- end -}}
---
apiVersion: batch/v1
kind: CronJob
{{ include "hmcts.metadata.v2" .}}
spec:
  schedule: "{{ $languageValues.schedule }}"
  {{- if $disableActiveClusterCheck }}
  startingDeadlineSeconds: {{ int $languageValues.startingDeadlineSeconds }}
  suspend: {{ int $languageValues.suspend }}
  {{- else }}
  {{ if eq $languageValues.suspend true }}
  suspend: true
  startingDeadlineSeconds: 5
  {{- else }}
  suspend: {{ not $activeCronCluster }}
  startingDeadlineSeconds: {{ $activeCronCluster | ternary $languageValues.startingDeadlineSeconds 5 }}
  {{- end }}
  {{- if $languageValues.concurrencyPolicy }}
  concurrencyPolicy: "{{ $languageValues.concurrencyPolicy }}"
  {{- end }}
  {{- if $languageValues.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $languageValues.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if $languageValues.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $languageValues.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
{{ include "job.spec.v2" . | indent 4}}
{{- end}}
