{{- $languageValues := deepCopy .Values}}
{{- if hasKey .Values "language" -}}
{{- $languageValues = (deepCopy .Values | merge (pluck .Values.language .Values | first) )}}
{{- end -}}
{{- $jobKind := (default $languageValues.kind  $languageValues.global.jobKind) -}}
{{ if (and $jobKind (eq $jobKind "CronJob")) }}
---
apiVersion: batch/v1
kind: CronJob
{{ include "hmcts.metadata.v2" .}}
spec:
  schedule: "{{ $languageValues.schedule }}"
  {{- if $languageValues.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{int $languageValues.startingDeadlineSeconds }}
  {{- end }}
  {{- if $languageValues.concurrencyPolicy }}
  concurrencyPolicy: "{{ $languageValues.concurrencyPolicy }}"
  {{- end }}
  {{- if $languageValues.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $languageValues.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if $languageValues.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $languageValues.failedJobsHistoryLimit }}
  {{- end }}
  {{- if $languageValues.suspend }}
  suspend: {{ $languageValues.suspend }}
  {{- end }}
  {{- if .Values.nodeSelector }}
  nodeSelector:
  {{ toYaml .Values.nodeSelector | indent 6 }}
  {{- end }}
  {{- if .Values.tolerations }}
  tolerations:
  {{ toYaml .Values.tolerations | indent 6 }}
  {{- end }}
  jobTemplate:
{{ include "job.spec.v1" . | indent 4}}
{{- end}}
