{{if and .Values.kind (eq .Values.kind "CronJob") }}
---
apiVersion: batch/v1beta1
kind: CronJob
{{ include "job.metadata" .}}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
{{ include "job.spec" . | indent 4}}
{{- end}}