{{- $languageValues := deepCopy .Values}}
{{- if hasKey .Values "language" -}}
{{- $languageValues = (deepCopy .Values | merge (pluck .Values.language .Values | first) )}}
{{- end -}}
{{- $jobKind := (default $languageValues.kind  $languageValues.global.jobKind) -}}
{{ if (and $jobKind (eq $jobKind "CronJob")) }}
{{- $globals := $languageValues.global -}}
---
apiVersion: batch/v1
kind: CronJob
{{ include "hmcts.metadata.v2" .}}
spec:
  {{- if $globals.concurrentCronJob }}
  schedule: "{{ $languageValues.schedule }}"
  suspend: false
  startingDeadlineSeconds: {{int default $globals.startingDeadlineSeconds $languageValues.startingDeadlineSeconds }}
  {{- else if and (not .Values.globals.concurrentCronJob) .Values.globals.activeCronCluster }}
  schedule: "{{ $languageValues.schedule }}"
  suspend: false
  startingDeadlineSeconds: {{int default $globals.startingDeadlineSeconds $languageValues.startingDeadlineSeconds }}
  {{- else if and (not .Values.globals.concurrentCronJob) (not .Values.globals.activeCronCluster) }}
  schedule: "{{ $languageValues.schedule }}"
  suspend: true
  startingDeadlineSeconds: 5
  {{- end }}
  {{- if $languageValues.concurrencyPolicy }}
  concurrencyPolicy: "{{ $languageValues.concurrencyPolicy }}"
  {{- end }}
  {{- if $languageValues.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $languageValues.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if $languageValues.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $languageValues.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
{{ include "job.spec.v1" . | indent 4}}
{{- end}}
