{{ if or (and .Values.overrideKind (eq .Values.overrideKind "CronJob")) (and (not .Values.overrideKind) (and .Values.global.job.kind (eq .Values.global.job.kind "CronJob"))) }}
---
apiVersion: batch/v1beta1
kind: CronJob
{{ include "job.metadata" .}}
spec:
  schedule: "{{ .Values.schedule }}"
  {{- if .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: "{{ .Values.startingDeadlineSeconds }}"
  {{- end }}
  {{- if .Values.concurrencyPolicy }}
  concurrencyPolicy: "{{ .Values.concurrencyPolicy }}"
  {{- end }}
  {{- if .Values.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: "{{ .Values.successfulJobsHistoryLimit }}"
  {{- end }}
  {{- if .Values.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: "{{ .Values.failedJobsHistoryLimit }}"
  {{- end }}
  {{- if .Values.suspend }}
  suspend: {{ .Values.suspend }}
  {{- end }}
  jobTemplate:
{{ include "job.spec" . | indent 4}}
{{- end}}