{{- $languageValues := (deepCopy .Values | merge (pluck .Values.language .Values | first) ) -}}
  {{- $jobKind := (default $languageValues.kind $languageValues.global.jobKind) -}}
{{ if (and $jobKind (eq $jobKind "Job")) }}
---
apiVersion: batch/v1
kind: Job
{{ include "hmcts.metadata.v2" .}}
{{ include "job.spec" .}}
  {{- end}}