{{- if .Values.configmap }}
---
apiVersion: v1
kind: ConfigMap
{{ include "jobs.metadata" .}}
data:
  {{- range $key, $val := .Values.configmap }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}